"""unique branch

Revision ID: 463a19a5496f
Revises: d609054a879a
Create Date: 2020-11-25 11:21:20.491641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '463a19a5496f'
down_revision = 'd609054a879a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'branch', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branch', type_='unique')
    # ### end Alembic commands ###
